---
- name: Validate variables
  ansible.builtin.import_tasks: validate.yml

- name: Validate prerequisites on KVM host
  ansible.builtin.import_tasks: preflight.yml

- name: Provision the Windows VM
  ansible.builtin.import_tasks: provision.yml

- name: Display provisioning summary
  ansible.builtin.import_tasks: summary.yml
