---
- name: Test PEM credential
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Show PEM path
      ansible.builtin.debug:
        msg: "PEM available at {{ tower.filename.template.pem }}"